modelParams: # full 62.36, 72.9, 76.87

  "SP":
    numActiveColumnsPerInhArea : 80 # checked
    columnCount : 2000 # ok
    "spatialImp": cpp
    "synPermConnected": 0.8 # checked
    "globalInhibition": 1 # ok
    "potentialPct": 0.4 # checked
    spVerbosity: 0
    seed: 1956
    synPermActiveInc: 0.01       # may be better, but ok
    synPermInactiveDec: 0.001    # may be better, but ok
    boostStrength: 0
    dutyCyclePeriod: 16
    potentialRadius: 16          # checked
    stimulusThreshold: 2


  TM:
    verbosity: 0
    columnCount: 2000                                   # ok
    cellsPerColumn: 2                                   # ok
    inputWidth: 2000
    seed: 1960
    temporalImp: tm_cpp

    activationThreshold: 8                              # checked
    minThreshold: 2                                     # ok
    newSynapseCount: 12                                 # on actThr
    initialPerm: 0.1                                    # checked
    connectedPerm: 0.45                                  # checked
    permanenceInc: 0.01                                 # checked
    permanenceDec: 0.01                                # on Inc
    predictedSegmentDecrement: 0.0005                   # on Inc
    checkSynapseConsistency: 0



  "SP2":
    columnCount : 2000                                 # ok
    inputWidth : 4000
    numActiveColumnsPerInhArea : 80                   # checked
    "spatialImp": cpp
    "synPermConnected": 0.3                            # checked
    "globalInhibition": 1                              # ok
    "potentialPct": 0.3                                # checked
    spVerbosity: 0
    seed: 1956
    synPermActiveInc: 0.1
    synPermInactiveDec: 0.1
    boostStrength: 2
    potentialRadius: 16                                # ok


  "CLS": # SDRCls : 77.3%, 85.3%
    "distThreshold": 4                                   # 4!!! if k=16
    maxCategoryCount: 10
    k : 16                                               # 16!!!
    distanceMethod: "rawOverlap"    # norm, rawOverlap, pctOverlapOfLarger, pctOverlapOfProto, pctOverlapOfInput
    #"alpha" : 0.2 # 0.5 = 59.2, 47.9, 62.1, 62.0, 62.5, 63.6, 61.7
    "verbosity" : 0
    #"implementation" : "cpp"

  "sensor":
    "mode": "bw"
    "background": 1
    memoryLimit: 1024

