modelParams:

  "SP":
    numActiveColumnsPerInhArea : 80
    columnCount : 2000
    "spatialImp": cpp
    "synPermConnected": 0.8
    "globalInhibition": 1
    "potentialPct": 0.4
    spVerbosity: 0
    seed: 1956
    synPermActiveInc: 0.01
    synPermInactiveDec: 0.001
    boostStrength: 0
    dutyCyclePeriod: 16
    potentialRadius: 16
    stimulusThreshold: 2


  TM:
    verbosity: 0
    columnCount: 2000
    cellsPerColumn: 2
    inputWidth: 2000
    seed: 1960
    temporalImp: tm_cpp

    activationThreshold: 8
    minThreshold: 2
    newSynapseCount: 12
    initialPerm: 0.1
    connectedPerm: 0.45
    permanenceInc: 0.01
    permanenceDec: 0.01
    predictedSegmentDecrement: 0.0005
    checkSynapseConsistency: 0



  "SP2":
    columnCount : 2000
    inputWidth : 4000
    numActiveColumnsPerInhArea : 80
    "spatialImp": cpp
    "synPermConnected": 0.3
    "globalInhibition": 1
    "potentialPct": 0.3
    spVerbosity: 0
    seed: 1956
    synPermActiveInc: 0.1
    synPermInactiveDec: 0.1
    boostStrength: 2
    potentialRadius: 16


  "CLS":
    "distThreshold": 4
    maxCategoryCount: 10
    k : 16
    distanceMethod: "rawOverlap"
    "verbosity" : 0

  "sensor":
    "mode": "bw"
    "background": 1
    memoryLimit: 1024

