modelParams:

  "SP":
    numActiveColumnsPerInhArea : 80                     # 3-4 % from colCnt
    columnCount : 2048                                  # 2048+
    "spatialImp": cpp
    "synPermConnected": 0.4 # 72.4, 72.4, 72.5, 74.0, 73.2, 73.8, 73.5, 74.7, 71.9, 73.4, 74.1
    "globalInhibition": 1
    "potentialPct": 0.2                                 # 0.1...0.2 !!!
    spVerbosity: 0
    seed: 1956
    synPermActiveInc: 0.04
    synPermInactiveDec: 0.005
    boostStrength: 1.5 # 74.7-2, 67.5 72.9, 72.7, 75.2, 74.7,73.6,

  TM:                                                   # 39% - current best
    verbosity: 0
    columnCount: 2048 # 64.7
    cellsPerColumn: 4                                   # 2 or 4
    inputWidth: 4096
    seed: 1960
    temporalImp: cpp
    newSynapseCount: 4                                  # 4 or 32!!! order matters    | lowb
    initialPerm: 0.1
    permanenceInc: 0.1
    permanenceDec: 0.005
    globalDecay: 0.0
    maxSynapsesPerSegment: 32                           # 32!!!
    maxSegmentsPerCell: 64                              # 64 or 8!!! order matters    | highb
    minThreshold: 32                                    # NO MATTER!!!
    activationThreshold: 4                              # 4!!!                        | lowb
    maxAge: 0

  "SP2":
    columnCount : 2048                                  # 2048!!! if 80
    inputWidth : 8192
    numActiveColumnsPerInhArea : 80                     # 80!!! if 2048
    "spatialImp": cpp
    "synPermConnected": 0.1 # 59.1, 61.6, 60.2, 58.3, 57.3
    "globalInhibition": 1
    "potentialPct": 0.1 # 56.4, 59.1
    spVerbosity: 0
    seed: 1956
    synPermActiveInc: 0.04
    synPermInactiveDec: 0.005
    boostStrength: 2.5  # 61.6, 59.9, 59.6, 61.0, 60.0, 62.1, 62.3, 60.7, 61.4, 59.4


  "CLS": # SDRCls : 77.3%, 85.3%
    "distThreshold": 4                                   # 4!!! if k=16
    maxCategoryCount: 10
    k : 16                                               # 16!!!
    distanceMethod: "rawOverlap"    # norm, rawOverlap, pctOverlapOfLarger, pctOverlapOfProto, pctOverlapOfInput
    #"alpha" : 0.2 # 0.5 = 59.2, 47.9, 62.1, 62.0, 62.5, 63.6, 61.7
    "verbosity" : 0
    #"implementation" : "cpp"

  "sensor":
    "mode": "bw"
    "background": 1

