modelParams:

  "SP":
    numActiveColumnsPerInhArea : 40
    columnCount : 2048
    "spatialImp": cpp
    "synPermConnected": 0.8
    "globalInhibition": 1
    "potentialPct": 0.4
    spVerbosity: 0
    seed: 1956
    synPermActiveInc: 0.01
    synPermInactiveDec: 0.001
    boostStrength: 0
    dutyCyclePeriod: 16
    potentialRadius: 16
    stimulusThreshold: 2

  AutoEncoder:
    inputWidth: 2048
    learningRate: 5e-3
    momentum: 0.9
    optimizer: adam
    hiddenSize: 128
    storageSize: 28

  Net:
    inputWidth: 128
    learningRate: 1e-3
    momentum: 0.9
    optimizer: adam
    maxCategoryCount: 10
    storageSize: 32
    seqSize: 6

  "sensor":
    "mode": "bw"
    "background": 0
    memoryLimit: 512
